### ISSUE TITLE
Systematic way to add new marker layers to map

### ISSUE THREAD

**Issue by ox-baloo** [the-scouts/geo_mapping#10]
Add functionality for scripts to be easily add marker layers and markers to maps. In particular to decide whether they are marker clusters or not, and then point to csv files to generate the markers.

**Comment by ox-baloo** [comment]
Should provide a more robust solution to #8

**Comment by ox-baloo** [comment]
Branch created to deal with this, will add comments next - but take a look

**Comment by AA-Turner** [comment]
closed by #22
