### ISSUE TITLE
Delete district_boundaries branch

### ISSUE THREAD

**Issue by AA-Turner** [the-scouts/geo_mapping#17]
**Is your feature request related to a problem? Please describe.**
I'm not sure where the district_boundaries branch came from, and there are no new features on it.

**Describe the solution you'd like**
For the branch to be deleted

**Additional context**
I'm not sure whether this branch was a precursor to the imd_reports stuff, or for something else?

**Comment by ox-baloo** [comment]
Apologies was a new branch #19
