### ISSUE TITLE
point_moved_by_km

### ISSUE THREAD

**Issue by AA-Turner** [the-scouts/geo_mapping#20]
**Is your feature request related to a problem? Please describe.**
PyCharm is complaining at me that point_moved_by_km has errors because arccos, arctan, and pi aren't recognised

**Describe the solution you'd like**
Not to have any errors!
- don't recognise the method as being used - can it be removed? (Or is it for future?)
- alternativley should they be numpy or shapely or whatever methods/properties?

**Additional context**
has_increase also not used

**Comment by ox-baloo** [comment]
#19 removed the point_moved_by_km function.
This function attempted to deal with updating lat long coordinates with distances in km. This problem was resolved by converting between different coordinate reference systems (notably WGS84 and OSGB36)
