### ISSUE TITLE
Adding automated testing

### ISSUE THREAD

**Issue by AA-Turner** [the-scouts/geo_mapping#4]
I think that we should look into some unit testing / wider automated testing for the whole suite, especially as the feature set grows

Partly also as a sanity check - when I change something I try to check that everything still works, but I am always liable to forget!

I don't know what's avalible/good to use at the moment but may look into this further in the future

Adam

**Comment by ox-baloo** [comment]
I had a look at this, worth a look in the future, basically revolves around hooks from the git push I think, which then requires someone somewhere on the internet to build the package and test. Would be good if we could get the test to happen on the git commit locally?

As a tactical solution I would suggest just trying to run some of the scripts and ensuring that they still work - I'll work out which ones should work and test the most things :)

**Comment by ox-baloo** [comment]
I think probably the next stage of this (after your excellent PR) and I really like pytest, is to create a 'test' dataset that we can publish and run the tests on (where we know what the answers should be).

**Comment by AA-Turner** [comment]
> (after your excellent PR)

Thanks!

> create a 'test' dataset that we can publish and run the tests on (where we know what the answers should be).

I've been looking into pytest fixtures and the ecosystem - I think there is a lot that can be done here, definitely
