### ISSUE TITLE
Code reviews

### ISSUE THREAD

**Issue by ox-baloo** [the-scouts/geo_mapping#6]
Alongside #4 and #5 - probably need to think about how we review each other's code ... more minds the better :)

**Comment by AA-Turner** [comment]
Indeed! There is a 'reviewer' option when creating pull requests - I have tried this now, though I'm not sure what it sends you/asks you to do

**Comment by ox-baloo** [comment]
That worked well I briefly read your diffs, just gives me some idea what is going on. 

Note to self I pushed some changes on master, and now realised that it would have been better for me to create a branch and then pull request it in probably, then it might be a bit more obvious (and possible for someone else to read)

**Comment by AA-Turner** [comment]
Great. Closing this issue now, though we can re-open it if needed
