### ISSUE TITLE
Add primary schools

### ISSUE THREAD

**Issue by AA-Turner** [the-scouts/geo_mapping#8]

**Comment by AA-Turner** [comment]
Closing due to #10.

@ox-baloo 
Should we maintain a list of requested features to add somewhere? (This came from a meeting of the Pears Project)

**Comment by ox-baloo** [comment]
Somehow need to link or differentiate between technical solution (being able to add marker layers and open appropriately formatted csv files to add markers to them) and the feature that this would provide (adding primary schools).

Perhaps the 'Add primary schools' is a valid 'issue' we just need to tag it appropriately (may need to add a new type of tag) and then reference the technical solution. My reason for this is there may be other features that rest on the same technical solution.
