### ISSUE TITLE
Postcode is valid but no postcode data

### ISSUE THREAD

**Issue by ox-baloo** [the-scouts/geo_mapping#9]
I have merged the Census data and ONS PD but obtain value '1' in postcode is valid column, but no ONS data. The validity of the postcode I think should be determined on whether it is in the ONS PD not whether it meets the regex criteria, as there are many postcodes that meet the regex criteria that aren't valid.

Note the postcode validity provides one function - to provide an easy thing to filter on (in my old version it meant I didn't try to look it up saving time, but the merge function removes that need).

Further whilst the cleaned postcode column was never used in the code, the merge was on the basis of not changing the data, but merely appending columns derived from elsewhere. Ideally the postcode inputted into census and the 'cleaned one' checked against the ONS PD should appear next to each other in the combined csv file - this makes checking easier.

**Comment by AA-Turner** [comment]
Oops!

Yes I have seen that now - I suppose a (much) more complicated regex could be implemented, but I think a poor solution.

Would we still want to keep the postcode is valid bool? If I reimplement the cleaned postcode column then this would perhaps be more useful and can still be filtered on in excel etc?

**Comment by ox-baloo** [comment]
Also I'd like the merge to deal with the fact that the 2019 postcode data is better than previous years postcode data. So if a Section has an invalid postcode in 2017 and 2018, but has a valid one in 2019, then populate the clean postcode field of the 2017 and 2018 records the the valid 2019 one (without overwriting the original data) and populate with the ONS fields from 2019 in the 2017 and 2018 records.

Ideally, it would be nice to extrapolate this to a Group level too, and to assign valid postcodes to the Group back to 2010 if there is a valid 2019 postcode.

I realise that this might take some time as it might be difficult to use the clever pandas merge and apply functions ... but is probably worth it for the historical analysis it gives?

Note all 2019 Colonies, Packs and Troops have valid postcodes :)

**Comment by AA-Turner** [comment]
Agreed.

Though, being really akward, Object IDs 
- 504643
- 442748
- 455342
are all 2019 Colonies/Troops without valid postcodes (as far as I can see)!

However 3 out of 23,000 and a bit isn't bad!

**Comment by AA-Turner** [comment]
As in PR, the first issue has been addressed, working on second imminently (tommorrow!)

**Comment by ox-baloo** [comment]
Ah yes, no postcode was submitted in those three cases ... okiedokie - there's no impending rush but if you're free and willing then by all means :)

**Comment by AA-Turner** [comment]
This might do something clever when #16 is merged, as I wrote `Closes: #Issue`, which seems to be another magic string
